### ISSUE TITLE
the path of src have problem

### ISSUE THREAD

**Issue by hahanigehaha233** [ottobonn/hexo-image-sizes#5]
I am newer in hexo and web code, I just install your package and write MarkDown like this
```
{% imsize %}
src: testpicture1.jpg
alt: Dell Precision 5510 repair
title: Cool beans!
profile: thumbnail
link: true
linkProfile: huge
{% endimsize %}
```

and here is my _config.yml
```
image_sizes:
  pattern: !!js/regexp /\.(gif|jpg|jpeg|png)$/i
  profiles:
    body:
      width: 700 # height will adjust to preserve aspect ratio
    thumbnail:
      width: 100 # Image will be cropped to a square
      height: 100
    huge:
      height: 1000
      allowEnlargement: true
  defaultProfile: body
  link: true
  linkProfile: huge
  useAltForTitle: true
```

but I can't get my image and the request url is error like this
```
Request URL: http://localhost:4000/_posts/testpicture/thumbnail-testpicture1.jpg
Request Method: GET
Status Code: 404 Not Found
```

Here is the url should be
```
Request URL: http://localhost:4000/2018/12/20/testpicture/testpicture2.jpg
Request Method: GET
Status Code: 200 OK
```

If you have any idea about this, please tell me：）
